// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function fact(n) {
  if (n !== 0) {
    return Math.imul(n, fact(n - 1 | 0));
  } else {
    return 1;
  }
}

console.log("Hello, BuckleScript and Reason!");

console.log("Factorial of 5 is " + String(fact(5)));

exports.fact = fact;
/*  Not a pure module */
