// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function valof(exp) {
  switch (exp.TAG | 0) {
    case /* Plux */0 :
        return valof(exp._0) + valof(exp._1) | 0;
    case /* Monus */1 :
        return valof(exp._0) - valof(exp._1) | 0;
    case /* Exp */2 :
        return exp._0;
    
  }
}

console.log("L0 test program 1 Plux(Monus(Exp(10), Exp(3)), Exp(8)) " + String(valof({
              TAG: /* Plux */0,
              _0: {
                TAG: /* Monus */1,
                _0: {
                  TAG: /* Exp */2,
                  _0: 10
                },
                _1: {
                  TAG: /* Exp */2,
                  _0: 3
                }
              },
              _1: {
                TAG: /* Exp */2,
                _0: 8
              }
            })));

exports.valof = valof;
/*  Not a pure module */
